version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./:/meu_chapa
    depends_on:
      - mongoClient
    links:
      - mongo
    ports:
      - "8080:8080"
      - "9229:9229"

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    env_file: .env
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  mongoClient:
    container_name: mongoClient
    image: mongo
    env_file: .env
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./.env:/usr/local/bin/.env
      - ./mongo-init.sh:/usr/local/bin/mongo-init.sh
    command:
      - /usr/local/bin/mongo-init.sh
