version: "3.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./:/meu_chapa
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "80:80"
      - "9229:9229"

  mongo:
    container_name: mongo
    restart: always
    image: mongo
    env_file: .env
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
